{% set name = "mkdocs-material" %}
{% set version = "6.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce2f4a71e5db49540d71fd32f9afba7645765f7eca391e560d1d27f947eb344c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.0
  run:
    - markdown >=3.2
    - mkdocs >=1.1
    - pygments >=2.4
    - pymdown-extensions >=7.0
    - python >3.0
  run_constrained:
    - mkdocs-material-extensions >=1.0

test:
  imports:
    - material

about:
  home: https://squidfunk.github.io/mkdocs-material/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  doc_url: https://squidfunk.github.io/mkdocs-material/
  dev_url: https://squidfunk.github.io/mkdocs-material/customization/

extra:
  recipe-maintainers:
    - monaldoj
    - marcelotrevisani
