{% set name = "mkdocs-material" %}
{% set version = "8.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aea074a5b368c8a27c8ae4fe72bd943176512b225541106797e367c62ce3f5a0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=3.2
    - mkdocs >=1.2.3
    - mkdocs-material-extensions >=1.0
    - pygments >=2.10
    - pymdown-extensions >=9.0
    - python >=3.6
    - jinja2 >=2.11.1

test:
  imports:
    - material

about:
  home: https://squidfunk.github.io/mkdocs-material/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  doc_url: https://squidfunk.github.io/mkdocs-material/
  dev_url: https://squidfunk.github.io/mkdocs-material/customization/

extra:
  recipe-maintainers:
    - monaldoj
    - marcelotrevisani
