travis:
  secure:
    BINSTAR_TOKEN: ww82dURiyhXRTkDK0VPOKinzc3qPVn3EPe0FIbvzdiqwk39G7AadSdo/9n3L80pozW3Dy2ANbgOyc46UCzr7mWTm5iwh7TvLW3QUmIQl7mt96FVRj0bAR2ipbXut7VfRhWzfLXHXGuRM+gYy/2VBtjv4uqaSZPUUJiECBsz6XWrjC5iE2tbJ073ItEIe00U//MPiw1w8k9cRvMb98yE/rRLXn6a4eU2sirBxfnyciFsmQvteybZTBvr1TfMTMhxLTPm/XJg0PEAeXvhzfH+k5UfKqYMTr0fvRkfHbIXddyQF32eDXrGR8KyeBgwa1DQ0t5xWO8syfBzDMxqIzFBlCmlQsSxe0C6+kND2IfwDEWLvxCkKYJyKc6B/PkTr/VknAJDGqdkbpOJmM7FM/XhdrK8SGe2wAGbHA9V5ZmKmBkKGXLzw9YwkoSJrxS0d7wPpkZ1RUv6ZDmcL4ijbDwraKfjQxr+uSZW+MBewjSBcMGBnjfUk4IzuGOwN+n+alG2biGAIhi+EeXOImQCpqrSJi0E5UTD3rnoEDiymEJNye/VQ8qGAJguaWNagbgemShGtyubCbRZD5UR8Lc/i17HHrGnq0zLtIWSoTMK2vTCkKNmAmiS0NriwXcfqU/26iVW6cgzDghDL+ib3jCtq9ws3hNsWQth05TFIHjDiYq3bXWo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
